### ISSUE TITLE
Mobile nav

### ISSUE THREAD

**Issue by markendley** [markendley/cmpltrbn#1]
When the window gets about this narrow and then the nav goes vertical.

We gotta make it mobile friendly

![screen shot 2018-03-06 at 8 57 40 pm](https://user-images.githubusercontent.com/6570606/37025942-1d6c0bf2-2181-11e8-8778-1530abd0f99a.png)

Can you make it work like this site's
http://www.shavershop.com.au/

We'll put the hamburger icon on the right hand side

And then when the menu is open
it looks like this, and then we can have submenu items

![screen shot 2018-03-06 at 9 01 43 pm](https://user-images.githubusercontent.com/6570606/37026152-a8245b28-2181-11e8-9300-64bced1218f3.png)
![screen shot 2018-03-06 at 9 01 38 pm](https://user-images.githubusercontent.com/6570606/37026153-a8630954-2181-11e8-9e6b-a8feef40c1b7.png)

**Comment by ugurcanbulut** [comment]
I don't know why but phpstorm committed much more files than I've worked with. So please let me know if this caused any problems. I will send you the files as zipped immediately. 

Anyway... I've created the mobile nav exactly like your sample. You can check the javascript from nav.js. By the way, don't know if it's something from my side, but Prepros JavaScript compiler creates a file named _global-dist.js in plugins folder but you put _global.min.js file in functions.php. So I commented your code and changed the path accordingly.
