### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by markendley** [markendley/cmpltrbn#10]
use http://realfavicongenerator.net/

[Landscape A.eps.zip](https://github.com/markendley/cmpltrbn/files/1847133/Landscape.A.eps.zip)

**Comment by ugurcanbulut** [comment]
Done!

**Comment by markendley** [comment]
No showing on staging site, I think you need to fix the image paths

**Comment by ugurcanbulut** [comment]
Yes, I've put dot like "./" and now it seems okay.
