### ISSUE TITLE
links to map Sydney office:

### ISSUE THREAD

**Issue by markendley** [markendley/cmpltrbn#12]
links to map Sydney office: https://www.google.com.au/maps/place/10+Regent+St,+Chippendale+NSW+2008/@-33.8844214,151.2004939,17z/data=!3m1!4b1!4m5!3m4!1s0x6b12ae26e6160c99:0x5d25f4c8fef06b33!8m2!3d-33.8844214!4d151.2026826 GC: https://www.google.com.au/maps/place/203%2F20+Lake+Orr+Dr,+Varsity+Lakes+QLD+4227/@-28.0745518,153.4183488,17z/data=!3m1!4b1!4m5!3m4!1s0x6b9103668842b1a5:0x22bc916603d7a5ab!8m2!3d-28.0745518!4d153.4205375

**Comment by ugurcanbulut** [comment]
Fixed!

(We have ACF fields for Office Location but tmp-contact.php is all static html. Do you want me to integrate the ACF fields? I've fixed the links manually btw.)

**Comment by ugurcanbulut** [comment]
Done!
