### ISSUE TITLE
with internet explorer there is a blank box on home page (attached prt sc)

### ISSUE THREAD

**Issue by markendley** [markendley/cmpltrbn#13]

**Comment by ugurcanbulut** [comment]
I don't see any attachment but I think you were talking about this one right?

<img width="1920" alt="screenshot 2018-03-27 13 07 59" src="https://user-images.githubusercontent.com/26007013/37962678-89ff52d0-31c4-11e8-94ab-538394f289d6.png">

I've fixed it! It meant to be the latest blog post but I forgot state to an if condition so it wasn't excluding the drafts. Anyway it's fixed now. The first box shows the latest post and second box shows the second latest post.
