### ISSUE TITLE
About icons on the bottom - align left and right (attached)

### ISSUE THREAD

**Issue by markendley** [markendley/cmpltrbn#14]
![icons - about2](https://user-images.githubusercontent.com/6570606/37897655-6469b3ea-3132-11e8-8b55-d0f55d44cf4d.jpg)

**Comment by ugurcanbulut** [comment]
Fixed! 

(Please let me know if you want me to remove that small padding left/right from the icons boxes. I kept those paddings in order to keep alignment proportions but if you want them to stick on left and right, I can remove the paddings too)
