### ISSUE TITLE
mobile designs

### ISSUE THREAD

**Issue by markendley** [markendley/cmpltrbn#15]
![mobile design](https://user-images.githubusercontent.com/6570606/37897694-81368278-3132-11e8-95b1-ad7abe9926f3.jpg)

**Comment by ugurcanbulut** [comment]
Fixed!

(I've fixed everything but the mobile nav. Actually I've fixed that too but I had to ask one thing before going further. According to the image above, I have to change the styling of the nav, but we have a "plus icon" which opens the sub-menu items. And if I want to remove the "plus icon" but make the main nav links to open the sub-menu, it means there won't be any access to main "About" and "Projects" pages.

So please let me know what you want me to do.)

**Comment by markendley** [comment]
Make it match the design, but keep the plug icon

**Comment by ugurcanbulut** [comment]
I've done some adjustments. Please let me know if it's okay or not.
