### ISSUE TITLE
footer ammends

### ISSUE THREAD

**Issue by markendley** [markendley/cmpltrbn#19]
6, Make the footer according to attached: Replace white with Blue (R 110, G 152,B 164) open map icon under GC address with link to google map. Move CAREERS below Sydney office contact.

![footer](https://user-images.githubusercontent.com/6570606/37983099-233ff25a-323e-11e8-8276-d2a5316e406c.jpg)

**Comment by ugurcanbulut** [comment]
Done! Plus office locations are dynamic now.
