### ISSUE TITLE
People page

### ISSUE THREAD

**Issue by markendley** [markendley/cmpltrbn#2]
These pages don't work well on mobile, it's gonna be so hard to make the text fit in the boxes.

![screen shot 2018-03-06 at 9 03 38 pm](https://user-images.githubusercontent.com/6570606/37026316-1f22afa4-2182-11e8-9390-80c3d30d75a9.png)

So.... for mobile lets make it work like this....

![screen shot 2018-03-06 at 9 04 27 pm](https://user-images.githubusercontent.com/6570606/37026358-4444ed6a-2182-11e8-8a02-92027a0b7f65.png)

As you can see all you gotta do is just turn off some styles (specifically the absolute positioning, and overflows), when the window reaches a certain width.

And then after that, just clean up the spacing a little.

**Comment by ugurcanbulut** [comment]
Done exactly how you wanted.
