### ISSUE TITLE
Project pages

### ISSUE THREAD

**Issue by markendley** [markendley/cmpltrbn#5]
These pages need a few more breakpoints

http://marke2.sg-host.com/complete-urban/projects/architecture/

As the window gets smaller I want these rectangles to maintain their crop and proportion. I don't want them to turn from landscape to portrait.

Architects are very nit-picky especially to how they crop their images.

![screen shot 2018-03-06 at 9 22 27 pm](https://user-images.githubusercontent.com/6570606/37027089-7d48736e-2184-11e8-93c6-2e190d2e3ec5.png)

**Comment by ugurcanbulut** [comment]
I've made all the necessary arrangements for each type of page and for each breakpoints. But feel free let me know if I've missed anything.
