### ISSUE TITLE
status options

### ISSUE THREAD

**Issue by markendley** [markendley/cmpltrbn#6]
The client said...

Can we please have the project status options changed to:

Ongoing
In Development
Design Phase
Design Completed
Currently Under Tender
In Construction
Completed

When you look at the ACF fields that I created for the project page, you'll see what I mean

**Comment by ugurcanbulut** [comment]
Done!

(I hope this is what you wanted) 

<img width="427" alt="screenshot 2018-03-27 14 49 57" src="https://user-images.githubusercontent.com/26007013/37965618-5f9543f6-31ce-11e8-9d5e-a9b7c46d3e51.png">
<img width="560" alt="screenshot 2018-03-27 14 50 08" src="https://user-images.githubusercontent.com/26007013/37965620-5fb29c80-31ce-11e8-962c-95a9318062f1.png">

**Comment by markendley** [comment]
correct
