### ISSUE TITLE
main project page

### ISSUE THREAD

**Issue by markendley** [markendley/cmpltrbn#7]
Hi Mark

Can you please edit this main project page where all the projects will be displayed http://marke2.sg-host.com/complete-urban/project/ to look like the project category pages with the thumbnail and font as per the project category pages (eg  http://marke2.sg-host.com/complete-urban/project_category/libraries-museums/ )

**Comment by ugurcanbulut** [comment]
I couldn't find the php file for this page: http://marke2.sg-host.com/complete-urban/project/

I thought it is page-ajax-load.php but the changes I've done didn't affect anything. Could you please guide me?

**Comment by markendley** [comment]
it'll either be index.php or arhcive.php

so what you need to do is create archive-project.php

**Comment by ugurcanbulut** [comment]
Partially done.

Sorry to bother you too much about this page but I didn't totally get how it works. I've created the basic loop, which I took reference from archive.php. But I couldn't manage to make the load more button work.

**Comment by markendley** [comment]
all good, I'll take over - thanks
